### ISSUE TITLE
Functional request

### ISSUE THREAD

**Issue by hahajaja** [nej-dot/loralist#1]

**Comment by nej-dot** [comment]
> You can check.safetensors file's metadata. There is a similar project here but it does not have a UI, thank you
> 
> https://github.com/by321/safetensors_util

Im not quite sure what you mean. Do you mean that you would like me to implement the functionality from that project into this?

**Comment by hahajaja** [comment]
Forgive me for being a programming idiot, I'd like you to make a UI for this project, if possible thanks
